# Neotoma Tables

The Neotoma Database contains more than 150 tables, and, as new proxy types get added or new metadata is stored, the number of tables may increase. As a result, this manual should not be considered the final authority, but it should provide nearly complete coverage of the database and its structure. In particular, do our best to divide tables into logical groupings: Chronology & Age related tables, Dataset related tables, Site related tables, Contact tables, Sample tables and so on.

## Site Related Tables

Tables for key geographic information relating to the dataset. Specifically geographic coordinates, geo-political units and any situational information such as images of the site itself.

* [`geopoliticalunits`](GeoPoliticalUnits)
* [`lakeparameters`](#lakeparameters)
* [`lakeparametertypes`](#lakeparametertypes)
* [`sitegeopolitical`](#SiteGeoPolitical)
* [`siteimages`](#SiteImages)
* [`sites`](#Sites)

## Dataset & Collection Related Tables

Tables related to complete datasets, or collections of samples. These include Collection information, but only refer to sites, since, as described in the Design Concepts, datasets are conceptually nested within sites, even if a site contains only a single dataset.

* [`accumulationrates`](#accumulationrates)
* [`aggregatedatasets`](#AggregateDatasets)
* [`aggregateordertypes`](#AggregateOrderTypes)
* [`collectiontypes`](#CollectionTypes)
* [`collectionunits`](#CollectionUnits)
* [`contextsdatasettypes`](#contextsdatasettypes)
* [`datasetdatabases`](#datasetdatabases)
* [`datasetdoi`](#datasetdoi)
* [`datasetpis`](#DatasetPIs)
* [`datasetpublications`](#DatasetPublications)
* [`datasets`](#Datasets)
* [`datasetsubmissions`](#DatasetSubmissions)
* [`datasetsubmissiontypes`](#DatasetSubmissionTypes)
* [`datasettaxagrouptypes`](#datasettaxagrouptypes)
* [`datasettaxonnotes`](#datasettaxonnotes)
* [`datasettypes`](#DatasetTypes)
* [`datasetvariables`](#datasetvariables)
* [`depenvttypes`](#DepEnvtTypes)

## Chronology & Age Related Tables

Information about the age models and chronological controls used to assess sample ages. Includes secondary information on tephras, and geochronological data types.

* [`agetypes`](#AgeTypes)
* [`aggregatechronologies`](#AggregateChronologies)
* [`aggregatesampleages`](#AggregateSampleAges)
* [`calibrationcurves`](#calibrationcurves)
* [`calibrationprograms`](#calibrationprograms)
* [`chroncontrolaccuracydirections`](#chroncontrolaccuracydirections)
* [`chroncontrolaccuracydistributions`](#chroncontrolaccuracydistributions)
* [`chroncontrolaccuracyranks`](#chroncontrolaccuracyranks)
* [`chroncontrolprecisionranks`](#chroncontrolprecisionranks)
* [`chroncontrolranks`](#chroncontrolranks)
* [`chroncontrols`](#ChronControls)
* [`chroncontrolscal14c`](#chroncontrolscal14c)
* [`chroncontroltypes`](#ChronControlTypes)
* [`chronologies`](#Chronologies)
* [`eventchronology`](#eventchronology)
* [`eventpublications`](#eventpublications)
* [`events`](#events)
* [`eventtypes`](#eventtypes)
* [`geochroncontrols`](#geochroncontrols)
* [`geochronology`](#Geochronology)
* [`geochronpublications`](#GeochronPublications)
* [`geochrontypes`](#GeochronTypes)
* [`radiocarbon`](#radiocarbon)
* [`radiocarboncalibration`](#RadiocarbonCalibration)
* [`radiocarbonmethods`](#radiocarbonmethods)
* [`relativeagepublications`](#RelativeAgePublications)
* [`relativeages`](#RelativeAges)
* [`relativeagescales`](#RelativeAgeScales)
* [`relativeageunits`](#RelativeAgeUnits)
* [`relativechronology`](#RelativeChronology)
* [`tephras`](#Tephras)

## Sample Related Tables

Information relating to individual samples or analysis units. This includes the age of the sample, the data content of the sample, and information relating to the physical condition or situation of the samples themselves.

* [`aggregatesamples`](#AggregateSamples),
* [`analysisunitaltdepths`](#analysisunitaltdepths)
* [`analysisunitaltdepthscales`](#analysisunitaltdepthscales)
* [`analysisunitlithostrat`](#analysisunitlithostrat)
* [`analysisunits`](#AnalysisUnits),
* [`data`](#Data)
* [`datataxonnotes`](#datataxonnotes)
* [`depagents`](#DepAgents)
* [`depagenttypes`](#DepAgentTypes),
* [`elementdatasettaxagroups`](#elementdatasettaxagroups)
* [`elementmaturities`](#elementmaturities)
* [`elementportions`](#elementportions)
* [`elementsymmetries`](#elementsymmetries)
* [`elementtaxagroupmaturities`](#elementtaxagroupmaturities)
* [`elementtaxagroupportions`](#elementtaxagroupportions)
* [`elementtaxagroups`](#elementtaxagroups)
* [`elementtaxagroupsymmetries`](#elementtaxagroupsymmetries)
* [`elementtypes`](#elementtypes)
* [`faciestypes`](#FaciesTypes),
* [`keywords`](#Keywords)
* [`lithology`](#Lithology)
* [`lithostrat`](#lithostrat)
* [`rocktypes`](#rocktypes)
* [`sampleages`](#SampleAges),
* [`sampleanalysts`](#SampleAnalysts),
* [`samplekeywords`](#SampleKeywords),
* [`samples`](#Samples),
* [`summarydatataphonomy`](#summarydatataphonomy)

## Specimen Related Tables

* [`fractiondated`](#fractiondated)
* [`repositoryinstitutions`](#repositoryinstitutions)
* [`repositoryspecimens`](#repositoryspecimens)
* [`specimendates`](#specimendates)
* [`specimendatescal`](#specimendatescal)
* [`specimendomesticstatustypes`](#specimendomesticstatustypes)
* [`specimengenbank`](#specimengenbank)
* [`specimens`](#specimens)
* [`specimensextypes`](#specimensextypes)
* [`specimentaphonomy`](#specimentaphonomy)
* [`taphonomicsystems`](#taphonomicsystems)
* [`taphonomicsystemsdatasettypes`](#taphonomicsystemsdatasettypes)
* [`taphonomictypes`](#taphonomictypes)

## Taxonomy Related Tables

Tables related to taxonomic information, phylogenetic information and ecological classifications. These tables also include hierarchy based on morphological or phylogenetic relationships.

* [`ecolgroups`](#EcolGroups)
* [`ecolgrouptypes`](#EcolGroupTypes)
* [`ecolsettypes`](#EcolSetTypes)
* [`externaltaxa`](#externaltaxa)
* [`formtaxa`](#formtaxa)
* [`synonyms`](#Synonyms)
* [`synonymtypes`](#SynonymTypes)
* [`synonymy`](#synonymy)
* [`taxa`](#Taxa)
* [`taxaalthierarchy`](#taxaalthierarchy)
* [`taxaalthierarchytypes`](#taxaalthierarchytypes)
* [`taxagrouptypes`](#TaxaGroupTypes)
* [`taxonpaths`](#taxonpaths)
* [`variablecontexts`](#VariableContexts)
* [`variableelements`](#VariableElements)
* [`variables`](#Variables)
* [`variableunits`](#VariableUnits)

## Individual Related Tables

Tables associated with individuals, institutions and organizations.

* [`collectors`](#Collectors),
* [`contacts`](#Contacts),
* [`contactstatuses`](#ContactStatuses)
* [`dataprocessors`](#dataprocessors)

## Publication Related Tables

Information relating to the publication of primary or derived data within the Neotoma Paleoecological Database.

* [`externalpublications`](#externalpublications)
* [`publicationauthors`](#PublicationAuthors),
* [`publicationeditors`](#PublicationEditors),
* [`publications`](#Publications),
* [`publicationtranslators`](#publicationtranslators)
* [`publicationtypes`](#PublicationTypes)

## Supporting Resources

* [`constituentdatabases`](#constituentdatabases)
* [`embargo`](#embargo)
* [`externaldatabases`](#externaldatabases)

## Isotope Data Management

* [`isobiomarkerbandtypes`](#isobiomarkerbandtypes)
* [`isobiomarkertypes`](#isobiomarkertypes)
* [`isoinstrumentation`](#isoinstrumentation)
* [`isoinstrumentationtypes`](#isoinstrumentationtypes)
* [`isomatanalsubstrate`](#isomatanalsubstrate)
* [`isomaterialanalyzedtypes`](#isomaterialanalyzedtypes)
* [`isometadata`](#isometadata)
* [`isopretreatmenttypes`](#isopretreatmenttypes)
* [`isosampleintrosystemtypes`](#isosampleintrosystemtypes)
* [`isosampleorigintypes`](#isosampleorigintypes)
* [`isosamplepretreatments`](#isosamplepretreatments)
* [`isoscaletypes`](#isoscaletypes)
* [`isospecimendata`](#isospecimendata)
* [`isosrmetadata`](#isosrmetadata)
* [`isostandards`](#isostandards)
* [`isostandardtypes`](#isostandardtypes)
* [`isostratdata`](#isostratdata)
* [`isosubstratetypes`](#isosubstratetypes)
* [`isovariablescaletypes`](#isovariablescaletypes)
